# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(717, 435)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 701, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.kilo = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.kilo.setObjectName("kilo")
        self.gridLayout.addWidget(self.kilo, 0, 0, 1, 1)
        self.inch = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.inch.setObjectName("inch")
        self.gridLayout.addWidget(self.inch, 1, 0, 1, 1)
        self.fahren = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.fahren.setObjectName("fahren")
        self.gridLayout.addWidget(self.fahren, 2, 0, 1, 1)
        self.mile = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.mile.setObjectName("mile")
        self.gridLayout.addWidget(self.mile, 0, 2, 1, 1)
        self.centi = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.centi.setObjectName("centi")
        self.gridLayout.addWidget(self.centi, 1, 2, 1, 1)
        self.cels = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.cels.setObjectName("cels")
        self.gridLayout.addWidget(self.cels, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "kilometer / mile"))
        self.label_2.setText(_translate("Dialog", "inch / centimeter"))
        self.label_3.setText(_translate("Dialog", "Fahrenheit / Celsius"))
